version: "3"
services:
  db1:
    image: postgres:9.6
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db1
    command:
      - "--max_prepared_transactions=10"
      - "--log_statement=all"
    volumes:
      - ./init-db1.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 4242:5432

  db2:
    image: postgres:9.6
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db2
    command:
      - "--max_prepared_transactions=10"
      - "--log_statement=all"
    volumes:
      - ./init-db2.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 4243:5432

  db3:
    image: postgres:9.6
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db3
    command:
      - "--max_prepared_transactions=10"
      - "--log_statement=all"
    volumes:
      - ./init-db3.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 4244:5432

